### ISSUE TITLE
Strip Triple-Slash Directives

### ISSUE THREAD

**Issue by Klustre** [scenery-io/stallion#4]
Strip Typescript's [Triple-Slash Directives](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) from the code when using `Send to Cavalry As…`. They're only useful in VSCode and pollute Cavalry's expression editor.

**Comment by Klustre** [comment]
[`/\/\/\/\s<reference.+\/>/g`](https://regexr.com/84nj1)

**Comment by yevgenymakarov** [comment]
Try this way:
```js
let regex = /^\/\/\/\s<reference.+\/>\n/;
text = text.replace(regex, "")
```
You need something like this for the line ending, though: `(\r\n|\n|\r)`.

**Comment by Klustre** [comment]
There's no need to make it more specific than necessary. The one you posted [only works in a single case](https://regexr.com/84oft) and fails when preceded by comments.
> Triple-slash directives are only valid at the top of their containing file. A triple-slash directive can only be preceded by single or multi-line comments, including other triple-slash directives. If they are encountered following a statement or a declaration they are treated as regular single-line comments, and hold no special meaning.
[Source](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)
